### ISSUE TITLE
scrappy appearance

### ISSUE THREAD

**Issue by tonipiano** [iamisti/mdDataTable#106]
Hi,

I need some help. 
I tried your data table component, but appearing in my environment is scrappy. A used your basic example. Can you tell me, what is the problem? 
I use: "angular": "~1.5.2", "angular-material": "~1.0.7",

![screenshot 2016-04-08 11 24 49](https://cloud.githubusercontent.com/assets/6460575/14379924/1c26897c-fd7d-11e5-975b-9169cbfaa40c.png)

Second problem is that you replace *default* angular start and end symbols in your code, but I’m using ‘{$’ and ‘$}’ symbols because of python-django. Can you prepare your code for using interpolateProvider?

Thanks for your help.
Tom

**Comment by iamisti** [comment]
Hi @tonipiano , can you please double check if this is still happening with the newest version?

Thanks!
