### ISSUE TITLE
removing line does not work

### ISSUE THREAD

**Issue by cunla** [iamisti/mdDataTable#107]
Hi, I have a table with changing model and when I removed a line it either duplicate all lines or does not remove the line.

see codepen [here](http://codepen.io/style81/pen/ONQVoy)

**Comment by iamisti** [comment]
Hi @cunla , thanks for reporting this.

This is a known issue with the `mdt-cell` directives.
Can you please try using `mdt-row` attribute instead? Please check the documentation and you'll figure it out. 

`mdt-cell` will be deprecated anyway. It's just increasing the complexity of the project and it's not really useful at all. Can you please verify it worked with `mdt-row`?

Thanks!

**Comment by webcane** [comment]
here is working mdt-row [codepen](http://codepen.io/webcane/pen/bwqxPR) example. But I dont' know howto get access to the row element, or row id inside mdt-cusstom-cell element.

**Comment by iamisti** [comment]
@webcane you can have access to it by using `rowId` scope variable which is a prefilled variable you can use in `mdt-custom-cell`
