### ISSUE TITLE
limit selectable-rows to one

### ISSUE THREAD

**Issue by themaniac** [iamisti/mdDataTable#108]
Is it possible to limit selectable-rows to one? i want to disable multiple selection on the table.

Thanks in advance

**Comment by rcheuk** [comment]
I implemented row selection limits...but it's still in progress. Feel free to examine my fork/branch though and see if the changes may help with your needs:

https://github.com/rcheuk/mdDataTable/commit/d33bcb26e68c2768df65334901e627caf7bf0eb2

You can pull the release from this commit.

**Comment by iamisti** [comment]
Hi @themaniac , this is a very good question. I haven't think about it before, but it's definitely a need in my eyes. Will put it on my list and will come back here after I did it.
