### ISSUE TITLE
Easy way to translate

### ISSUE THREAD

**Issue by Kail0** [iamisti/mdDataTable#111]
Hey there,

is it possible to translate  "Rows per page" ?  

Thanks

**Comment by FlorianBurgevin** [comment]
+1

**Comment by iamisti** [comment]
Good catch!
I'm on it.

**Comment by iamisti** [comment]
@Kail0 , @FlorianBurgevin Fixed and shipped with v1.6.5!

How you can use:
```html
<mdt-table
            paginated-rows="{isEnabled: true, rowsPerPageValues: [5,10,20,100]}"
            mdt-translations="{
                'rowsPerPage': 'Rows per page'
            }">
        <mdt-header-row>
            <mdt-column align-rule="left">Dessert (100g serving)</mdt-column>
            <mdt-column align-rule="right">Calories</mdt-column>
            <mdt-column align-rule="right">Fat (g)</mdt-column>
            <mdt-column align-rule="right">Carbs (g)</mdt-column>
            <mdt-column align-rule="right">Protein (g)</mdt-column>
            <mdt-column align-rule="right">Sodium (mg)</mdt-column>
            <mdt-column align-rule="right">Calcium (%)</mdt-column>
            <mdt-column align-rule="right">Iron (%)</mdt-column>
        </mdt-header-row>
        <mdt-row ng-repeat="nutrition in nutritionList">
            <mdt-cell>{{nutrition.name}}</mdt-cell>
            <mdt-cell>{{nutrition.calories}}</mdt-cell>
            <mdt-cell>{{nutrition.fat}}</mdt-cell>
            <mdt-cell>{{nutrition.carbs}}</mdt-cell>
            <mdt-cell>{{nutrition.protein}}</mdt-cell>
            <mdt-cell>{{nutrition.sodium}}</mdt-cell>
            <mdt-cell>{{nutrition.calcium}}</mdt-cell>
            <mdt-cell>{{nutrition.iron}}</mdt-cell>
        </mdt-row>
    </mdt-table>
```

**Comment by rvt** [comment]
Hate to hijack a thread, but is it also possible to use the angular translate? (https://angular-translate.github.io)
In my code I use the translation filter like this : `<h2 class="modal-title">{{'Deny User' | translate}}</h2> `and I get the UI translated to the correct language. 
Is something like this possible? For example:

```
mdt-translations="{
                'rowsPerPage': '{{'Rows per Pager' | translate}}'
            }">
```

**Comment by johannesvaltonen** [comment]
With `mdt-translations` attribute you can at least do the translation in the controller:

HTML:
`mdt-translations="$ctrl.gridTranslations"`

Controller:
`gridTranslations = {
    "rowsPerPage": $translate.instant("search.grid.results-per-page")
}`

But unfortunately the `mdt-row-paginator-error-message` and `mdt-row-paginator-no-results-message` attributes do not seem to be supporting angular translate at all. They cannot even be bound to controller for doing the translation there.

Additionally the word _"of"_ in pagination (e.g. _"1-10 of 27"_) cannot be translated.

**Comment by cristianoap** [comment]
Isn't would possible add the translate filter/attribute to translate all strings? So the dev may attach her favorite translation tool (angular-gettext, angular-translate, etc).
