### ISSUE TITLE
Typo in README example

### ISSUE THREAD

**Issue by JesterJeffrey** [iamisti/mdDataTable#114]
Pasting and running the provided example at the end of the README produces this error:
"Error: [$compile:ctreq] Controller 'mdtTable', required by directive 'mdtColumn', can't be found!"

Issue at line 24 as mdt-column tag not properly closed:
`<mdt-column sortable-rows-default>    
Fat (g)
        </mt-column>`

Should read:
`<mdt-column sortable-rows-default>    
Fat (g)
        </mdt-column>`        
      
Also, `<mdt-cell>Frozen Joghurt</mdt-cell>` would only display with quotes, `<mdt-cell>"Frozen Joghurt"</mdt-cell>`.

**Comment by iamisti** [comment]
Fixed.
