### ISSUE TITLE
Default selected rows

### ISSUE THREAD

**Issue by mohasin69** [iamisti/mdDataTable#117]
I am setting selected flag true while pushing data in storage (that is in TableDataStorageService.prototype.addRowData() ) for default selection. Still it is not working. I have another isDeleted flag in option list which is working fine. 

It is getting overridden from somewhere. 
Please help..

**Comment by mohasin69** [comment]
Resolved..

**Comment by iamisti** [comment]
Sorry for the delay but I'm glad you resolved it by yourself!

**Comment by valhermes** [comment]
How you can call TableDataStorageService.prototype.addRowData()?
