### ISSUE TITLE
Example of mdt-row-paginator call back function?

### ISSUE THREAD

**Issue by lrodriguezrullan** [iamisti/mdDataTable#118]
I am trying to use a paginator call back function, but am getting an error.  

I assume that the call back function must return a promise that in turn must return an array of rows, based on the current page index and page size. Am I right?

Can you provide an example of a paginator call back function?

Thanks for the great work!

**Comment by lrodriguezrullan** [comment]
I was able to resolve the error as described in issue #24. However, I am still unable to display the contents of the table using mdt-row-paginator.

**Comment by lrodriguezrullan** [comment]
Here is my JS code: 

`$scope.paginatorCallback = function(page, pageSize) {

      var results = [];

      var startIndex = (page - 1) * pageSize;
      var endIndex = startIndex + pageSize;

      for (var i = startIndex; i < $scope.nutritionList.length && i <
        endIndex; i++) {
        results.push($scope.nutritionList[i]);
      }

      console.log("results: %O", results);

      return $q.when(results);

    };`

The paginatorCallback function is getting called and returning the promise with the correct values, however no values are displayed.

Here is the HTML:

`  <md-card flex="100" flex-lg="80">
    <mdt-table
      paginated-rows="{isEnabled: true, rowsPerPageValues: [5,10,20,100]}"
      mdt-row-paginator="paginatorCallback(page, pageSize)"
      mdt-row-paginator-error-message="Error happened during loading nutritions."
      mdt-row="{
        'table-row-id-key': 'id',
        'column-keys': [ 'name', 'calories', 'fat', 'carbs', 'protein', 'sodium', 'calcium', 'iron']
      }">
      <mdt-header-row>
        <mdt-column>Dessert</mdt-column>
        <mdt-column>Calories</mdt-column>
        <mdt-column>Fat</mdt-column>
        <mdt-column>Carbs</mdt-column>
        <mdt-column>Protein</mdt-column>
        <mdt-column>Sodium</mdt-column>
        <mdt-column>Calcium</mdt-column>
        <mdt-column>Iron</mdt-column>
      </mdt-header-row>
    </mdt-table>
  </md-card>`

**Comment by lrodriguezrullan** [comment]
I found a fix!  I changed the paginatorCallback function as follows: 

```
    $scope.paginatorCallback = function(page, pageSize) {

      var results = [];

      var startIndex = (page - 1) * pageSize;
      var endIndex = startIndex + pageSize;

      for (var i = startIndex; i < $scope.nutritionList.length && i <
        endIndex; i++) {
        results.push($scope.nutritionList[i]);
      }

      console.log("results: %O", results);

      return $q.when({
        results: results,
        totalResultCount: $scope.nutritionList.length
      });

    };
```

**Comment by iamisti** [comment]
Did the last comment help you?

**Comment by iamisti** [comment]
@lrodriguezrullan sorry for the delay, you figured it out, that's great!

**Comment by ArvindNikam76** [comment]
How do we apply filters in table data
i want to apply filters for table data 
 mdt-row="{
        'table-row-id-key': 'id',
        'column-keys': [ 'name', 'calories', 'fat', 'carbs', 'protein', 'sodium', 'calcium', 'iron']
      }">
