### ISSUE TITLE
Controller 'mdTable', required by directive 'mdCell', can't be found!

### ISSUE THREAD

**Issue by imraqes** [iamisti/mdDataTable#123]
Normally my table is working fine. I disabled back button by following code
```
function disableBack() { $window.history.forward(1); }
        $window.onpopstate = disableBack();
```
So when I click on back button and previous page having any table then I am getting this error.

> Controller 'mdTable', required by directive 'mdCell', can't be found!

**Comment by iamisti** [comment]
Hi @imraqes , thanks for your comment.

Can you please double check if the issue is still happening with the latest release?

**Comment by imraqes** [comment]
Hi @iamisti 

the issue was solved. it's working without errors now. Thanks..
