### ISSUE TITLE
_ is not defined

### ISSUE THREAD

**Issue by avjiang** [iamisti/mdDataTable#125]
i have followed all the instructions, but when i try to invoke the table, suddenly it gives me this error _ is not defined. can somebody help me please?

**Comment by acuero-ssb** [comment]
Hi!

Add this:

``
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/0.10.0/lodash.min.js"></script>

[http://stackoverflow.com/questions/13556010/referenceerror-is-not-defined](url)
