### ISSUE TITLE
mdt-cell html-content EROOR

### ISSUE THREAD

**Issue by eduardosanzb** [iamisti/mdDataTable#126]
Hello, when using the mdt-cell with the html option to insert a custom button interrupt Angular and break the project. 
My code:
`<mdt-row ng-repeat="data in vm.tableData">
      <mdt-cell>{{data.period}}</mdt-cell>
      <mdt-cell>{{data.subject}}</mdt-cell>
      <mdt-cell>{{data.group}}</mdt-cell>
      <mdt-cell>{{data.title}}</mdt-cell>
      <mdt-cell html-content="true">
        <button>lols</button>
      </mdt-cell>
      
      
    </mdt-row>`
[image screenshot](https://img42.com/Zl6Wr+)
![error](https://img42.com/Zl6Wr+)

**Comment by sstewart199** [comment]
Same issue, has a solution: https://github.com/iamisti/mdDataTable/issues/102
