### ISSUE TITLE
how to call ng-Click on on mdt-custom-cell attribue.

### ISSUE THREAD

**Issue by shriharry** [iamisti/mdDataTable#144]
I have table like below 

```
<mdt-table virtual-repeat="true" sortable-columns="true" 
mdt-row="{
     'data': filteredItems,  
     'table-row-id-key': 'id',
     'column-keys': ['name', 'calories', 'fat', 'carbs', 'protein', 'sodium', 'calcium', 'iron']
    }">
<mdt-header-row>
```
after adding all mdt-column, I have created mdt-custom-cell and wanted to call scope function on ng-click event like this

```
<mdt-custom-cell ng-click="viewFats(id)" column-key="fat">
                        <span>{{ value | getViewerFat}}</span>
</mdt-custom-cell>
```

But my viewFats() function from scope is never get called.  As I have used custom filter 'getViewerFat' as well on data therefore I don't want to pass click event with value from controller.

Is it right way to call viewFats()? Also by reading documentation , I just got that I can only access scope variable 'value' in mdt-custom-cell?  So in this case can't I call scope viewFats() function like this?

**Comment by iamisti** [comment]
@shriharry sorry for the delay.
There is a way, I build a new feature recently. Now you can access your local scope variables by referencing to `clientScope` within `mdt-custom-cell`.

**Your example will look the following**
```html
<mdt-custom-cell ng-click="clientScope.viewFats(id)" column-key="fat">
                        <span>{{ value | getViewerFat}}</span>
</mdt-custom-cell>
```

Although your method which accepts and *id* (`clientScope.viewFats(id)`) will have a problem. You can not access the associated row data at the moment, but I'm releasing tomorrow an improvement, so you will be able to do that as well.

**Comment by vinnybod** [comment]
@iamisti did you ever get around to releasing the improvement to allow us to get the row-id in a custom cell?

**Comment by iamisti** [comment]
Sorry @vinnybod to make it so long. Now it is possible to get the `id` of a row by referring `rowId` in the `mdt-custom-cell` directive. Showing it with your example it will look the following (added to version **v1.8.3**)

```html
<mdt-custom-cell ng-click="clientScope.viewFats(rowId)" column-key="fat">
    <span>{{ value | getViewerFat}}</span>
</mdt-custom-cell>
```

**Comment by vinnybod** [comment]
@iamisti this did not seem to solve my problem.

I have mdt-table like so.
`<mdt-table mdt-row="{'data': filteredItems,
                      'table-row-id-key': 'id',
                      'column-keys': ['[address', 'city', 'state', 'zip 'reports']}"
               sortable-columns="true"
               animate-sort-icon="true"
               ripple-effect="true">`

Then I have tried a combination of things for the custom cell.
`      <mdt-custom-cell column-key="reports" html-content="true">
        <md-button class="md-primary" ng-click="clientScope.switchView(rowId,'/report')">Test</md-button>
      </mdt-custom-cell>
`
the above code does not work because ` [ngTransclude:orphan] Illegal use of ngTransclude directive in the template! No parent directive that requires a transclusion found.`
When I try the same, but passing in a value that isn't "rowId" it does not give that error and will switch the view.

I also tried putting the ng-click directly on the mdt-custom-cell tag but nothing is triggered from clicking in the cell that way.

**Comment by gerome0123** [comment]
@vinnybod is your ng-click working now????

**Comment by celorodovalho** [comment]
@vinnybod
I have the same problem here!

**Comment by vinnybod** [comment]
@gerome0123 @celorodovalho my problem kind of strayed away from the original question, so I will take a look at some of the more recent issues opened for a solution and if needed I will open a new issue in the near future.

**Comment by iamisti** [comment]
Hi guys, I'm going to take this over and will try to solve it at the weekend.

**Comment by vinnybod** [comment]
@gerome0123 @celorodovalho @iamisti I was able to get ng-click working on an md-button within an mdt-custom-cell (codepen below). The only obvious issue is that the button does not actually format.

http://codepen.io/vinnybod/pen/woBzMp

**Comment by gerome0123** [comment]
@vinnybod thank you very much

**Comment by neslinesli93** [comment]
Found out that it passes the wrong rowId when combined with sorting... Anyone has a workaround?

**Comment by traafat** [comment]
when filter (client side or ajax) rowId is incorrect, in my case i dont use sort , just setting table-row-id-key and filter using ajax, with each new result set the rowId takes the index of the first row.

this pen explains it 
http://codepen.io/vinnybod/pen/eBmeer

type is search : "kitkat"
results filters correctly
if you click on the icon notice the id is always 601 as supposed to be the id of the item resulted.

Please help...
thouths

**Comment by gerome0123** [comment]
@vinnybod how did your rowId works???

**Comment by vinnybod** [comment]
@gerome0123 check out the codepen I provided. Make sure `'table-row-id-key'` matches whatever your id field is named in the object.

As for the followup about filtering and sorting, I just checked my own implementation and it turns out that I get the same issue @traafat mentioned above.

**Comment by gerome0123** [comment]
i did can you check my issue i need a hand here </3 #273
