### ISSUE TITLE
Injection Error when Including the module.

### ISSUE THREAD

**Issue by LeonardoMinatiCrispyBacon** [iamisti/mdDataTable#145]
I started using this module today, but when I include it it gives me an injection error and i'm stuck on it. I've followed the steps:

1) bower install mdDataTable
2) Included scripts as folows:
```
script(defer, src="/bower_components/mdDataTable/dist/md-data-table.js")
script(defer, src="/bower_components/mdDataTable/dist/md-data-table-templates.js")
```

3) Included css as follows:
`link(rel="stylesheet" href="/bower_components/mdDataTable/dist/md-data-table-style.css")`

4) Added dependency:

`var app = angular.module('app', ['ngRoute', 'ngCookies', 'ngResource', 'ngMaterial', 'mdDataTable', 'ui-notification', 'ngFileUpload'])`

ERROR: Uncaught Error: [$injector:modulerr]

Unfortunately i can't make it work. Can you help me please?

Thanks,

Leonardo

**Comment by iamisti** [comment]
Hello, can you please try loading the templates first and then the core library?
e.g.:
`
script(defer, src="/bower_components/mdDataTable/dist/md-data-table-templates.js")
script(defer, src="/bower_components/mdDataTable/dist/md-data-table.js")
`

**Comment by LeonardoMinatiCrispyBacon** [comment]
Unfortunately it does not solve the problem 😞

**Comment by LeonardoMinatiCrispyBacon** [comment]
@iamisti I solved the problem adding `script(defer, src="//cdnjs.cloudflare.com/ajax/libs/angular-material-icons/0.5.0/angular-material-icons.min.js")` to my scripts include. Hope it can help to fix the problem on the module. Keep on and congratulations, fantastic job here! 👍  😄
