### ISSUE TITLE
mdt-custom-cell works incorrect

### ISSUE THREAD

**Issue by Shmublon** [iamisti/mdDataTable#148]
The variable "value" has  incorrect value, you can see it on your DEMO http://iamisti.github.io/mdDataTable/, "Ajax html cell support" 
`<mdt-custom-cell column-key="protein">
            <span ng-class="{'red': value > 5, 'green': value <= 5}">{{value}}</span>
        </mdt-custom-cell>`

on the screen you can see the value of protein always 7
http://static.xscreenshot.com/2016/08/17/10/screen_0bf95cfe44aa143cbeaa0b5abc530da7

**Comment by webcane** [comment]
In my PC it's Ok. Maybe You have old brouser?

**Comment by iamisti** [comment]
@Shmublon 
Yes it was but I already fixed it few weeks before.
But thank you very much for reporting it!
