### ISSUE TITLE
Start demo project locally?

### ISSUE THREAD

**Issue by RootsMJ** [iamisti/mdDataTable#150]
This might be a very dumb question, but I've been trying to get the demo project to work locally so that I can debug the scripts, since I'm having an issue with the Ajax Search version of mdDataTable, but I can't seem to get it to work. The scripts all link to codepen that can't be found and I don't know which is which.
[See this Stackoverflow question ](http://stackoverflow.com/questions/39073987/angular-mddatatable-pagination-is-not-working-properly) for my initial issue.

Am I missing something obvious?

**Comment by Nedyt** [comment]
+1

**Comment by iamisti** [comment]
@RootsMJ, @Nedyt  sorry for the late answer.

Just clone the repository,
`npm install`
`npm install -g gulp`
`npm install -g bower`
`bower install`
`gulp` 

and when you do `gulp`, just wait until it finishes it's work and then open a browser with `localhost:9000`

**Comment by RootsMJ** [comment]
Hi thanks for the reply. Sorry, I'm quite new to the whole gulp/bower world. After running these commands I'm getting this error:

> events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: You need to have Ruby and Compass installed and in your system PATH for this task to work.


I've tried bower install Ruby and Compass but I'm guessing it's Ruby the language? Can't really understand why I would need that to run a js app?

**Comment by iamisti** [comment]
No, you right. It's a but f*cked up but you need to install Ruby for the style compilation.
Install ruby: https://www.ruby-lang.org/en/documentation/installation/

Then if you installed it, run the following:
`gem install compass`

then if everything ends,
`gulp` should work.

**Comment by RootsMJ** [comment]
aha ok, so it's for the Sass? Then I get it. thanks!

**Comment by iamisti** [comment]
Yes it is for Sass

**Comment by RootsMJ** [comment]
It worked great! You can close this ticket and thanks for your help!
Just a heads up, it seems there's authorization issues with the API you're using for the Ajax demo. Tried your live demo and same issue there.

**Comment by iamisti** [comment]
You're welcome.

Yes, they banned me for a while. I already wrote them an email.  They will enable it hopefully within 1-2 days. But you right, with a custom you can use it.
