### ISSUE TITLE
ng-repeat not clearing table

### ISSUE THREAD

**Issue by JonasRafn** [iamisti/mdDataTable#152]
Why is the table not cleared on model change when using ng-repeat? 
If i change the array to a new array, it just appends the new entries without clearing the table first. 

Am i doing something wrong, is this a feature or a bug?

See this pen for example: http://codepen.io/jonasrafn/pen/EgYkjw

**Comment by arhang** [comment]
got same issue

**Comment by JonasRafn** [comment]
have found out that it s a known bug with no current solution. But there is a work around instead of using mdt-row directive use the mdt-row attribute on mdt-table directive. 
See this codepen for example: http://codepen.io/jonasrafn/pen/ZpzoZq
And documentation here: https://github.com/iamisti/mdDataTable#table-attributes

**Comment by vladjerca** [comment]
How is this a solution?

I don't see a way of being able to inject HTML into a cell using this.

**Comment by gerome0123** [comment]
@JonasRafn is there possible to filter in mdt-rows?
