### ISSUE TITLE
empty rows on virtual scroll

### ISSUE THREAD

**Issue by mikila85** [iamisti/mdDataTable#154]
Empty rows on virtual scroll and error in console for every row like this.
([On demo too](http://codepen.io/iamisti/pen/qbxLEQ))
sometimes work sometimes not..
![image](https://cloud.githubusercontent.com/assets/3965957/18170169/fa6db5ce-7065-11e6-9041-f0555340229e.png)

**Comment by iamisti** [comment]
@mikila85 Thanks, I'm aware of that. It's most probably because of an angular material issue.

https://github.com/angular/material/issues/9275

I filed the issue, let's hope they fix it soon!

**Comment by mikila85** [comment]
Wow thx you are awesome! I hope they fix it soon I'm having hard time now doing it by my self and cant use yours because of this bug

**Comment by mikila85** [comment]
Hi bro, they have a fix for us hope it will work!
Do you understand what he means, or how to implement it?

**Comment by iamisti** [comment]
Chekced it, still not a solution we can use to fix the bug :( I replied on the thread.

**Comment by mikila85** [comment]
bro how you solved the md-virtual-repeat-container in tbody controller problem?...

**Comment by iamisti** [comment]
@mikila85 good news.
I was able to solve the issue locally. Will make a release tomorrow afternoon, so you guys can use it without any issue.

**Comment by mikila85** [comment]
Awesome bro!!! Looking forward to trying it out!

**Comment by iamisti** [comment]
Fixed with v1.6.10
