### ISSUE TITLE
Callback when selecting/deselecting all rows

### ISSUE THREAD

**Issue by vladjerca** [iamisti/mdDataTable#156]
I think the code should be updated so that 'selected-row-callback' is triggered when checking/unchecking the box in the header. Seems kind of useless to have that in the header if there is no way of retrieving the selected values.

**Comment by iamisti** [comment]
It works exactly in the way you just described. Just check the codepen example.
http://codepen.io/iamisti/full/OMvbMj/

(the toaster is down there ,make sure it's in your view)

**Comment by vladjerca** [comment]
Hi,

So the following problems:

1. The CodePen examples throw an inejctor error (all demo's fail).
2. I'm currently using version 1.6.6 of mdDataTable (this was the latest version at the moment I opened the issue) and the row callback never triggers when selecting ALL of the elements. If I select each individual element it works as expected.
