### ISSUE TITLE
ng-repeat table update

### ISSUE THREAD

**Issue by vladjerca** [iamisti/mdDataTable#157]
Reference: #152

As the old issue was closed, even though it is in no way a solution.

**Comment by vladjerca** [comment]
I've just discovered now:
```html
<mdt-cell html-content="true">
```
Now my question is the following. Why have two cell states?
 
Why not have html enabled by default and be done with it?

I think that this flag just over complicates things and even works as expected with ng-repeat updates being on available this way.

**Comment by isaiastavares** [comment]
Sorry for my English. 
I solved using track by id.

Example:

```
<mdt-row ng-repeat="usuario in vm.usuarioList track by usuario.id">
                    <mdt-cell>{{usuario.nome}}</mdt-cell>
                    <mdt-cell>{{usuario.email}}</mdt-cell>
                    <mdt-cell>{{usuario.permissao}}</mdt-cell>
                    <mdt-cell html-content="true">
                        <div class="crop">
                            <md-button class="md-icon-button md-primary" aria-label="Editar"
                                       ng-click="vm.editar(usuario)">
                                <md-icon md-svg-icon="../images/icon/ic_mode_edit_black_18px.svg"></md-icon>
                            </md-button>
                        </div>
                    </mdt-cell>
                </mdt-row>
```

**Comment by iamisti** [comment]
@vladjerca probably you right, I need to rethink this concept with html contents. Originally if was due performance reasons and also because  I need a way to detect content types due the sorting feature.

**Comment by iamisti** [comment]
@vladjerca I also don't recommend to use `mdt-row` element directive. I suggest you to use `mdt-row` attribute directive of `mdt-table`

**Comment by gerome0123** [comment]
track by id is not working when the table is inside of angular tabs it keeps repeating
