### ISSUE TITLE
I cannot load ng module in my app

### ISSUE THREAD

**Issue by sinhpn92** [iamisti/mdDataTable#165]
My app have error load module:

```
<link rel="stylesheet" href="css/modules/angular-material.min.css">
<script src="js/modules/angular.min.js"></script>
<script src="js/modules/angular-animate.min.js"></script>
<script src="js/modules/angular-aria.min.js"></script>
<script src="js/modules/angular-messages.min.js"></script>
<script src="js/modules/angular-material.min.js"></script>
<script src="js/app.js"></script>
<link rel="stylesheet" href="css/modules/md-data-table-style.css">
<script src="js/modules/md-data-table-templates.js"></script>
<script src="js/modules/md-data-table.js"></script>
```

`var module = angular.module('my-app', [ 'ngMaterial','mdDataTable']);`

I receive an error: `angular.min.js:6 Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=my-app&p1=Error…20(http%3A%2F%2Flocalhost%3A8080%2Fjs%2Fmodules%2Fangular.min.js%3A21%3A19)`

**Comment by iamisti** [comment]
You need to have `ngSanitize` as well and it will work

`https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-sanitize.js`
