### ISSUE TITLE
How to show actionIcons on header the table card?

### ISSUE THREAD

**Issue by CesaRamirez** [iamisti/mdDataTable#170]
![image](https://cloud.githubusercontent.com/assets/12446271/18721813/58494e7c-7fef-11e6-876d-61d9ba0f3bdd.png)

**Comment by iamisti** [comment]
@CesaRamirez 

This feature is not yet implemented. But it's in the plan for the following releases.

**Comment by horelvis** [comment]
Hi, there are some workaround to do this before next releases?
