### ISSUE TITLE
Ordering columns with ajax calls

### ISSUE THREAD

**Issue by mateosss** [iamisti/mdDataTable#172]
It is common that some APIs already support the *ordering* parameter in the backend, and it is applied to the entire database query.
Would it be possible to bind a custom method when sorting a column for make a custom call to the API instead of the current default behaviour?

**Comment by iamisti** [comment]
Currently you can not use proper ordering with the ajax support. But it's currently under implementation and will be available soon.

**Comment by orekav** [comment]
I would love it, it will be an amazing feature

**Comment by iamisti** [comment]
@orekav @mateosss yes it is under development, will be ready soon. Stay sharp! :)

**Comment by iamisti** [comment]
I'm working on it at the moment, will be ready soon to release.

**Comment by iamisti** [comment]
Built in with `mdt-row-paginator`, check out the documentation!

Released you can use the latest version (at the moment it's `v2.0.1` )

**Comment by mateosss** [comment]
Amazing, thank you!
