### ISSUE TITLE
Accessing controller scope within mdt-custom-cell

### ISSUE THREAD

**Issue by mateosss** [iamisti/mdDataTable#174]
Is there a way to do this? or is it mandatory to be limited to an empty scope with only the *value* property?

I need to execute a function located in my controller, from a button inside a mdt-custom-cell.

**Comment by iamisti** [comment]
Hi @mateosss , no it shouldn't be limited. I just didn't think about that case  before. I'm fixing it

**Comment by iamisti** [comment]
Now you can use your local scope with using `clientScope` variable inside `md-custom-cell`

**Comment by mateosss** [comment]
Thanks!
