### ISSUE TITLE
table-row-id in mdt-custom-cell

### ISSUE THREAD

**Issue by Thomas0816** [iamisti/mdDataTable#178]
Is it possible to get the table-row-id in a mdt-custom-cell?
The reason for this is, that I have an id for every line. Now i want to implement a click event for this line to open details for this element in a new window.

**Comment by iamisti** [comment]
You can find the closed `tr` and get the id for it.
just create a custom attribute directive in your `mdt-custom-cell` and do something like this `element.closest('tr').attr('id')`

Let me know if it doesn't work.

**Comment by iamisti** [comment]
Now you can get it by referencing `rowId` in `mdt-custom-cell`.

**Comment by traafat** [comment]
this is not working for me.
 when i get rowId - assigning table-row-id-key = my record id and do ajax pagination on search this rowId does not change and it gives me the first Id in the initial list

**Comment by Djiggy** [comment]
same as traasfat, rowId is not updated after filter / sort

**Comment by animesh1987** [comment]
+1

**Comment by animesh1987** [comment]
Have the same issue, right now have a workaround where I define the column key as '_id' and then pass it as a reference in a function attached to ClientScope. Will be good to get the rowId reference on pagination/filter/sort.
