### ISSUE TITLE
Specify a class for each row in ajax pagination

### ISSUE THREAD

**Issue by JalalSordo** [iamisti/mdDataTable#179]
I like your library it's pretty straightforward, but I have a requirement where I need to add a style for each row for the table (e.g: color ).

My question is, how can I specify a class for each row according to an expression; something that could be closer to this (just guessing):

<mdt-table ... mdt-row-class="{'red-row':data.calories>10}" ...>

Thanks in advance.

**Comment by iamisti** [comment]
Hi @JalalSordo ,

Do you need to colorise your rows depending on the data, or is it random or what is your case?
At the moment you can only add id for each row, but adding class can be easily added as well if there is a need.

**Comment by JalalSordo** [comment]
Yes my row coloring depends on data, also i need ajax pagination, do you think it's possible ?

**Comment by iamisti** [comment]
For sure it is, I'll do something on this weekend for you.

**Comment by iamisti** [comment]
Absolutely. It'll publish a new release and it will be there in the next few hours

**Comment by iamisti** [comment]
Ready to use with `v1.7.0`

```html
<!-- in your view -->
<mdt-table
            mdt-row-paginator="paginatorCallback(page, pageSize)"
            mdt-row-paginator-error-message="Error happened during loading nutritions."
            mdt-row="{
                'table-row-class-name': rowClassNameCallback,
                'column-keys': [
                    'name',
                    'calories',
                    'fat',
                    'carbs',
                    'protein',
                    'sodium',
                    'calcium',
                    'iron'
            ]}">

    <mdt-header-row>
            <mdt-column align-rule="left">Dessert (100g serving)</mdt-column>
            <mdt-column align-rule="right">Calories</mdt-column>
            <mdt-column align-rule="right">Fat (g)</mdt-column>
            <mdt-column align-rule="right">Carbs (g)</mdt-column>
            <mdt-column align-rule="right">Protein (g)</mdt-column>
            <mdt-column align-rule="right">Sodium (mg)</mdt-column>
            <mdt-column align-rule="right">Calcium (%)</mdt-column>
            <mdt-column align-rule="right">Iron (%)</mdt-column>
    </mdt-header-row>
```

```javascript
//in your controller
$scope.rowClassNameCallback = function(row){
        return row.name;
};
```
