### ISSUE TITLE
editable-field doesn't work

### ISSUE THREAD

**Issue by DanieleRatti** [iamisti/mdDataTable#19]
Is the editable-field already under development? I can't get it working

**Comment by iamisti** [comment]
yes it's under development. I'm still working on the first milestone: https://github.com/iamisti/md-data-table/milestones

But in the next milestone it will be in. Within 1-3 weeks.

**Comment by DanieleRatti** [comment]
Happy to heard this. Good work

**Comment by iamisti** [comment]
Thanks, I'm trying my best. Will update this ticket, once it's in.

**Comment by vamceedhar** [comment]
Can I please know when it will be available?

**Comment by iamisti** [comment]
I didn't start to develop that particular feature, and I'm not able to say deadline for 100% for sure. But any contribution for the project are still greatly appreciated.

**Comment by jaoued** [comment]
Hi,

Any updated status for this feature ?

Regards.

**Comment by iamisti** [comment]
Sorry guys, it is. But as a one-man-army I can't really do a lot of things. But weekend comes, will have more time to work on different improvements and bug fixes.

**Comment by jaoued** [comment]
Put paypal.me button, i will pay you a coffee :+1:

**Comment by iamisti** [comment]
A coffee is always great :) Thanks ;)

**Comment by iamisti** [comment]
@DanieleRatti @jaoued 
Introduced with v1.4.0
Check out demo page to see how it works.
There is still a lot of improvements can be done, but the basic functionality is there.

**Comment by jaoued** [comment]
Oh thanks :+1: , i will check this.
