### ISSUE TITLE
sorting / sortby method

### ISSUE THREAD

**Issue by getglad** [iamisti/mdDataTable#194]
I am trying to make a more generic table, one where I might not know all the property names.

I made a sample fork of the 'sortable columns' example on codepen (For simplicity, I removed the ID property):
http://codepen.io/getglad/pen/pEaOdk

The biggest change I have made is the rows section now looks like this:
```
<mdt-row ng-repeat="nutrition in nutritionList">
  <mdt-cell html-content="true" ng-repeat="(k, v) in nutrition">
    {{v}}
  </mdt-cell>
</mdt-row>
```

The table displays fine, but I have broken the sorting somehow. Now, no matter what column I try to sort, only 'calories' ends up getting sorted. 

Any tips?

I wondered if I should be using `mdt-custom-cell`, but the example includes only a `cell` markup, nothing for `row`. 

```
<mdt-custom-cell column-key="protein">
  <span ng-class="{'red': value > 5, 'green': value <= 5}">{{value}}</span>
  <span ng-click="clientScope.myMethodToExecute()">click here</span>
</mdt-custom-cell>
```

Maybe I'm missing something?

**Comment by iamisti** [comment]
@getglad that's interesting. Give me some time to check it and try to resolve your issue.

**Comment by iamisti** [comment]
I've managed to do something similar what you need. Hopefully it'll help you.

http://codepen.io/iamisti/pen/ozqWWB

The idea:
- generating the keys based on the first item in your controller
- passing and constructing the `mdt-row` attribute directive's input still in controller level
- passing the constructed object to the view.

**Comment by getglad** [comment]
oh nice - thanks!

**Comment by iamisti** [comment]
My pleasure to help you ;)

**Comment by simonaco** [comment]
Hi,

I came across the same kind of requirement - making the table more generic. In my case, I don't know the column names and some of them could have a custom template - say you need to add a view/delete button in the last table column. How would you handle this? The problem that I have now is that ng-include is not working in mdt-custom-cell.
