### ISSUE TITLE
vertical scroll

### ISSUE THREAD

**Issue by dspublic** [iamisti/mdDataTable#20]
I see, there is a table horizontal scrollbar for column scroll.
Do you plan to develop a vertical scrollbar feature with fixed row header?

**Comment by iamisti** [comment]
if there is a need, for sure we can have it.

**Comment by dspublic** [comment]
I think,it would be great. Thank you

**Comment by anderskristian** [comment]
I agree. It would be very nice to be able to position the table-header in a fixed position.
I have tried the current version on both Crome, Safari and Firefox.
There is problems in the samples. http://iamisti.github.io/md-data-table/ does not work well:
Crome: Vertical scroll will try to scroll entire page. (Less good)
Crome: Horisontal scroll will work inside the table (Good)
Firefox: Vertical scroll vill try to scroll entire page (Same as Crome, not good)
Firefox: Horisontal scroll. Does NOT work. The canvas is violated. Table will violate the right margin by 7 centimeters.
Safari: (As crome)

**Comment by iamisti** [comment]
Hi @anderskristian , I made something for you: http://codepen.io/iamisti/pen/mVOKEw
