### ISSUE TITLE
Change column value 

### ISSUE THREAD

**Issue by guihendias** [iamisti/mdDataTable#203]
Hello folks, Is there a way to dinamically change the column value ? I'm trying to do a weekly calendar that I need to change the days. 

Thanks.

**Comment by iamisti** [comment]
Hi @guihendias , it is not possible yet, but for a weekly calendar, don't you just need fixed column values? Or how did you plan to do it? 

Maybe an example, link or something to see what you want to achieve.

**Comment by guihendias** [comment]
Clicking the arrow buttons it will change the week. Then, to make it easier for the user to control their own data, I would like to show the day in the columns. 

In this table, employees will be able to see and control how much they worked in some activity, at this moment only by week.

![print_screen](https://cloud.githubusercontent.com/assets/13769443/19571003/1228b34e-96db-11e6-80fc-dae4cf6fc7a1.jpg)

**Comment by iamisti** [comment]
Seems like you need different tables if you want to do something like that. And it also makes sense, they are different tables as far as I see on your example.

If you change the state when changing the weeks, then your view will gets rebuild and you'll have what you want.

Another solution to somehow use ng-if and make sure you activate and deactivate it. With this the view will get destroyed and rebuild where you placed ng-if.

**Comment by guihendias** [comment]
Got it, I'll use states to rebuild the table.

Thanks 😄 .

**Comment by iamisti** [comment]
You're welcome. Let me know if you encountered any problems.
