### ISSUE TITLE
Sortable column doesn't work with percent sign

### ISSUE THREAD

**Issue by laurentperroteau** [iamisti/mdDataTable#206]
Hi,

In your [demo](http://iamisti.github.io/mdDataTable/), in the Sortable Columns exemple the rows of table are not sorted correctly on sort Calcium and Iron column.

Instead of using the [Lodash function "sortby"](https://lodash.com/docs/4.16.4#sortBy), you should use "Natural Sorting" (in [TableDataStorageFactory.js](https://github.com/iamisti/mdDataTable/blob/master/app/modules/main/factories/TableDataStorageFactory.js#L105)).

I tried sort using [this Stackoverflow response](http://stackoverflow.com/questions/25101038/underscore-js-sort-an-array-of-objects-alphanumerically#answer-25119691) and it's work perfect: 

`var res = _.sortByNat(this.storage, function(obj) { return obj.data[index].value; });`

Sorry, I haven't time these days to create a Pull Request (maybe in the middle of the week)

**Comment by iamisti** [comment]
hi @laurentperroteau ,

thanks for your question. I've recently improved sorting so you might want to look at it again.
Now you can specify 'comparator' if you are using a fixed dataset. I think it's working fine now.
You can even specify which columns you want to have as a sortable columns. Check out the docs pls :)

**Comment by laurentperroteau** [comment]
Perfect, I try the `column-sort="{ comparator: $ctrl.columnComparator}"` function, it's work perfect, thanks again.

**Comment by iamisti** [comment]
Great! Enjoy it! :)
