### ISSUE TITLE
Error: $injector:modulerr Module Error when i try to inject mdDataTable in my app

### ISSUE THREAD

**Issue by DOCbrink** [iamisti/mdDataTable#211]
Hi, 
I'm trying to include the mdDataTable lib to my angular app.
So i added the three libs => doesn't work.
So i added two other libs (sanitize and material-icons) => doesn't work.
So i opened the demo on codepen and saw that i must load underscore and lodash to but => doesn't work. =(

here my code : 

`

    <script src="../common/js/libs/jquery.3-1-0.min.js"></script>
    <script src="../common/js/libs/angular.1-5-8.min.js"></script>
    <script src="../common/js/libs/angular-ui-router.0-2-8.min.js"></script>
    <script src="../common/js/libs/angular-cookies.1-5-8.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.8/angular-sanitize.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.10.1/lodash.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/angular-material-icons/0.5.0/angular-material-icons.min.js"></script>
    
    
    <link href="../common/css/libs/angular-material.1-1-1.min.css" rel="stylesheet">
    <script src="../common/js/libs/angular-messages.1-5-9.min.js"></script>
    <script src="../common/js/libs/angular-animate.1-5-8.min.js"></script>
    <script src="../common/js/libs/angular-aria.1-5-8.min.js"></script>
    <script src="../common/js/libs/angular-material.1-1-1.min.js"></script>

    
    <link href="../common/css/libs/md-data-table-style.1-8-0.min.css" rel="stylesheet">
    <script src="../common/js/libs/md-data-table-templates.1-8-0.min.js"></script>
    <script src="../common/js/libs/md-data-table.1-8-0.min.js"></script>

    
    <script>
        var app = angular.module("myapp", ["ui.router", "ngMaterial", "ngAnimate", "ngMessages", "ngCookies", "mdDataTable"]);
    </script>
`

it throw me always the same error when i try to inject "mdDataTable" =>

`Uncaught Error: [$injector:modulerr] `

Am I doing something wrong ?

**Comment by DOCbrink** [comment]
ok, it seems to be i copy past "md-data-table.1-8-0.min.js" in "md-data-table-templates.1-8-0.min.js".
It work correctly (and i removed loadash and underscore).

**Comment by iamisti** [comment]
great, I'm glad you figured it out.
