### ISSUE TITLE
mdt-custom-cell inside ngRepeat creating new rows

### ISSUE THREAD

**Issue by jackywhlee** [iamisti/mdDataTable#215]
Hey, nice library you have here. I'm trying to create a column of buttons in a mdt-table that will hopefully take in a toggle button to disable/enable the row. I couldn't find a working example for the documentation of mdt-custom-cell with ng-repeat, but could anyone take a look? It's creating new duplicated rows and refuses to populate the `coupon.currency` column.

```
  <mdt-table
    mdt-row="{'data': couponList, 'table-row-id-key': 'coupon._id', 'column-keys': ['coupon.promo', 'coupon.desc', 'coupon.start_date', 'coupon.end_date', 'coupon.currency', 'coupon.discount_value', 'coupon.discount_per']}">
    <mdt-header-row>
      <mdt-column align-rule="left">Promo code</mdt-column>
      <mdt-column align-rule="left">Description</mdt-column>
      <mdt-column align-rule="left">Start date</mdt-column>
      <mdt-column align-rule="left">End date</mdt-column>
      <mdt-column align-rule="left">Currency</mdt-column>
      <mdt-column align-rule="left">Discount value</mdt-column>
      <mdt-column align-rule="left">Discount %</mdt-column>
    </mdt-header-row>
    <mdt-row ng-repeat="coupon in couponList">
      <mdt-cell>{{coupon.coupon_code}}</mdt-cell>
      <mdt-cell>{{coupon.description}}</mdt-cell>
      <mdt-cell>{{coupon.start_date}}</mdt-cell>
      <mdt-cell>{{coupon.end_date}}</mdt-cell>
      <mdt-custom-cell column-key="coupon.currency">
        <span>click{{value}}{{rowId}{{coupon.currency[0]}}}</span>
      </mdt-custom-cell>>
      <mdt-cell>{{coupon.discount_value}}</mdt-cell>
      <mdt-cell>{{coupon.percent_off}}</mdt-cell>
    </mdt-row>
  </mdt-table>
```

**Comment by jackywhlee** [comment]
Scratch that, i figured it out after digging through the demos

**Comment by iamisti** [comment]
That's cool 👍

**Comment by gerome0123** [comment]
where did you get the coupon._id in your table-row-id-key? teach me master :)

**Comment by jackywhlee** [comment]
@gerome0123 coupon._id is a key inside my couponList array. that id can be anything as long as it exists inside the array, like numbers or strings. i could use `coupon.promo` as the table-row-id-key if i wanted and get the id by {{value}} and passing that inside a ng-click="".

i never managed to get rowId working so I had to use value

**Comment by iamisti** [comment]
`{{rowId}}` works only if you defined `mdt-table-row-id` inside `mdt-row` table attribute (!not the `<mdt-row>` element directive)

**Comment by gerome0123** [comment]
@iamisti can you give an example?? :)

**Comment by traafat** [comment]
from source

  * @example
     * <pre>
     *  <mdt-table>
     *      <mdt-header-row>
     *          <mdt-column>Product name</mdt-column>
     *          <mdt-column>Price</mdt-column>
     *      </mdt-header-row>
     *
     *      <mdt-row
     *          ng-repeat="product in products"
     *          table-row-id="{{product.id}}">
     *          <mdt-cell>{{product.name}}</mdt-cell>
     *          <mdt-cell>{{product.price}}</mdt-cell>
     *      </mdt-row>
     *  </mdt-table>
     * </pre>
     */
