### ISSUE TITLE
Using setTimeout to call the selectedRowCallback

### ISSUE THREAD

**Issue by cleverjam** [iamisti/mdDataTable#216]
Is there a particular reason why you are using `setTimeout` instead of `$timeout` here:

**app/modules/main/features/SelectableRowsFeature.js**
```javascript
        SelectableRowsFeature.prototype.onCheckboxChange = function(){
            var that = this;
            // we need to push it to the event loop to make it happen last
            // (e.g.: all the elements can be selected before we call the callback)
            setTimeout(function(){
                that.$scope.selectedRowCallback({
                    rows: that.ctrl.dataStorage.getSelectedRows()
                });
            },0);
        };
```

I am having trouble with this because my callback function updates are not triggering the digest cycle, using `$timeout` would fix the issue...

**Comment by iamisti** [comment]
Hi @cleverjam , no there were no reason behind. I'll change it and make it work for you.

Did you actually tried to change it to `$timeout` and it worked for you then?

**Comment by cleverjam** [comment]
I tried briefly yesterday and it worked. If you give me a couple hours I can make sure it works(just double check) and then send you a pull request

**Comment by iamisti** [comment]
already done, sorry I didn't read your comment :) 
Fixed with `v.2.1.0`

**Comment by cleverjam** [comment]
Cool, thanks!
