### ISSUE TITLE
How to get two column-keys in one mdt-custom-cell

### ISSUE THREAD

**Issue by gerome0123** [iamisti/mdDataTable#218]
here's my code for the details :)
```
mdt-table  
   sortable-columns="true" 
   animate-sort-icon="true" 
   ripple-effect="true" 
   mdt-row="{
       'data': filteredItems, 
       'table-row-id': 'id' , 
       'column-keys': [ 'id', 'name', 'branch.name', 'department.name', 'email']
   }"

  mdt-header-row
    mdt-column align-rule="center" ID
    mdt-column align-rule="center" Name
    mdt-column align-rule="center" Branch Name
    mdt-column align-rule="center" Department Name
    mdt-column align-rule="center" Email
```

```
mdt-custom-cell column-key="[name]"
  a ng-href="employees/{{INEEDTHEIDHERE}}" target="_self" {{value}}`
```

how to get the id value to my mdt-custom-cell(name) so i can click some employee information to redirect in another page???

**Comment by iamisti** [comment]
id can be found by referencing `rowId` variable inside mdt-custom-cell, and you can even do more if you need by using `clientScope` variable which is pointing to your scope (so you can easily create a function which based on an id returns whatever you need there).

Something like that:
```html
<mdt-custom-cell column-key="[name]"
  a ng-href="employees/{{rowId}}" target="_self" {{value}}`
```

**Comment by gerome0123** [comment]
mdt-table  sortable-columns="true" animate-sort-icon="true" ripple-effect="true" mdt-row="{'data': filteredItems, 'table-row-id-key': 'id' , 'column-keys': ['name', 'branch.name', 'department.name', 'email']}"

  mdt-header-row
    mdt-column align-rule="center" ID
    mdt-column align-rule="center" Name
    mdt-column align-rule="center" Branch Name
    mdt-column align-rule="center" Department Name
    mdt-column align-rule="center" Email

    mdt-custom-cell column-key="name"
      a ng-href="employees/{{rowId}}" target="_self" {{value}}

i try this but nothing happen??? can u give me an example with codepen :) thanks in advance

**Comment by iamisti** [comment]
Here it is http://codepen.io/anon/pen/JbogEj
You probably have a different property which identifies your row id.

so look closely on this property setup: `'table-row-id-key': 'id'` <-- you might want to change it whatever is in your response, whatever identifies your each row in your JSON object.

**Comment by gerome0123** [comment]
i just update my mddadatatable version
