### ISSUE TITLE
how to hook up save funcion of comment to the backend ?

### ISSUE THREAD

**Issue by jpca999** [iamisti/mdDataTable#220]
so i basically transported the demo code lines to my project.
All seem to work fine but i still need to hook up the save functions to talk to my backend. Any direction / guide woudl be helpful. 

```javascript
save: function (input) {
   if(input.$modelValue === 'Donald Trump') {
       input.$invalid = true;
       console.log( '116 -  calling the save function'); 
       return $q.reject();
    }
    
    if(input.$modelValue === 'Bernie Sanders') {
        return dessert.comment = 'FEEL THE BERN!'
    }
    
    arrSelectedProperties.comment = input.$modelValue;
},
```

**Comment by iamisti** [comment]
@jpca999 how is your setup looking like? Which demo code did you use? 

The best would be to create a codepen example (just form the demo one), and inject your way of trying, so I can help you even easier.
But injecting code here is also fine, just it's harder to see what the problem is.

**Comment by jpca999** [comment]
I'm using this demo.  http://codepen.io/anon/pen/BjvLVJ?editors=1010

**Comment by iamisti** [comment]
Lol, you are using another repository, you aren't using mine... 
Mine is pretty simple to use (if you use it :D )

**Comment by jpca999** [comment]
i've seen your like , which one to use to edit the content of a 1 cell inside a row ?
