### ISSUE TITLE
Format cell value

### ISSUE THREAD

**Issue by ralph-wermke** [iamisti/mdDataTable#224]
I want to format (use angular filters) the value in model before it gets displayed.
I just found mdt-custom-cell.
Is that the way to go just to add a formatter?

**Comment by vinnybod** [comment]
If you are defining your rows using an ng-repeat you can do it easily by doing something like
```<mdt-row ng-repeat="food in foods">
<mdt-cell>{{food.expiration | date: "MMMM dd, y"></mdt-cell></mdt-row>```

or if you are using the something like the search function and aren't using mdt-cell then you can do what you said and just add the formatter to a custom cell

```<mdt-custom-cell column-key="expiration">{{value | date:  date: "MMMM dd, y"></mdt-custom-cell>```

**Comment by ralph-wermke** [comment]
OK, thanks. I overlooked the first option.
Then I don't have to change so much in my code.
I going to change my current implementation from https://github.com/daniel-nagy/md-data-table to this.
But just changing imports and dependency leads to a problem with DI which can not solve at the moment.

**Comment by iamisti** [comment]
Perfect answer, thanks @vinnybod !

**Comment by gerome0123** [comment]
@vinnybod is there possible to create a button in mdt-cell??
