### ISSUE TITLE
Sorting of number is not correct

### ISSUE THREAD

**Issue by Tommatheussen** [iamisti/mdDataTable#226]
Using the table like shown in the following example the numbers get sorted as a string, not as a number.

```
<mdt-table>
  <mdt-header-row>
    <mdt-column column-sort="true">String values</mdt-column>
    <mdt-column column-sort="true">Numeric values</mdt-column>
  </mdt-header-row>

  <mdt-row ng-repeat="valin vm.values">
    <mdt-cell>{{ val.stringVal }}</mdt-cell>
    <mdt-cell>{{ val.numericVal}}</mdt-cell>
  </mdt-row>
</mdt-table>
```

Where vm.values holds the following: 
```
[
  {
    "stringVal": "aaaaa"
    "numericVal": 1
  },
  {
    "stringVal": "bbbbb"
    "numericVal": 3
  },
  {
    "stringVal": "ccccc"
    "numericVal": 12
  }
]
```

In this example the string values get sorted correctly, but the numeric values get sorted like strings (1, 12, 3).
Using the other syntax (`mdt-row: { 'data': vm.values, 'column-keys' }`) does seem to sort the numeric correctly.

EDIT: After some digging around, it seems the value gets transformed to a string in this line: https://github.com/iamisti/mdDataTable/blob/master/app/modules/main/directives/body/mdtCellDirective.js#L60

**Comment by iamisti** [comment]
Dear @Tommatheussen ,

I think it's not a bug, since you are passing a value with transclusion. The problem with transclusion is that you loose the type of the value. (or at least it's not checked during transclusion). It would be an additional effort to determine the type which is not really needed in my opinion. `<mdt-row>` element will be anyway deprecated with the next release, so please try to avoid using it.

There is still a possibility to make the sorting work even in this case, using the `comparator` attribute on `<mdt-column>` directive, having your number logic built in.

**Comment by Tommatheussen** [comment]
Thanks for the explanation
I did use custom comparators on the mdt-columns now, but if you say mdt-row will be deprecated, I guess it's best to move away from it.

The problem I had with using inline mdt-row was the custom html content combining 2 values.
I tried to use a function like described with the row_id variable, but it seems the number always got an undefined value. Perhaps I was doing it wrong :p using the row_id interpolated in the html did show the correct number though, so it seems like the function got executed before the number was actually set or something?

**Comment by iamisti** [comment]
Yeah, so if you tried it with using `<mdt-row>` element attribute, there is a high chance why it doesn't work. That directive is already missing few features.

can you please try `mdt-row` attribute on `mdt-table` element directive and get back to me if it's still doesn't work?

**Comment by Tommatheussen** [comment]
I have tried using the `mdt-row` attribute in the table itself, but there I experienced the issue with the ID, it seems I got the same issue as describe in https://github.com/iamisti/mdDataTable/issues/218

If you modify your codepen to call a function inside of the custom cell (just a simple one, that prints the id), you will notice the id is undefined

**Comment by iamisti** [comment]
Working for me: http://codepen.io/anon/pen/aBORBZ

**Comment by Tommatheussen** [comment]
Aah, I see, you're using `arguments[0]`, whereas I was using the rowId variable in the function, will try it like this later today, thank already! :)

**Comment by iamisti** [comment]
no, you can even use the normal function parameters and it should work.
You're welcome!

**Comment by Tommatheussen** [comment]
Ok, I got it to work now, it seems like it just doesn't play nicely when using `controller-as`, ty again for the help
