### ISSUE TITLE
Table holding on to past results - revealed when sorting

### ISSUE THREAD

**Issue by allumbra** [iamisti/mdDataTable#25]
I am using the table to hold search results.  When I perform a search, the table behaves as I expect.  However, if I do a column sort, I will see results from previous searches mixed in.  
Is there a way to clear out past results from the table?  Clearly, replacing the model object is not doing the trick :)

**Comment by iamisti** [comment]
Sorry for the late answer. Somehow i didnt read this issue yet. Can u please conform that this behaviour is still happening? Can u pls try out with v0.2 (which is in master atm, but wprth a try)

**Comment by iamisti** [comment]
@allumbra Figured out that it's a serious issue because of the way how angular transcludes elements.
I'm trying to fix it but it might take longer time to fix it.
If I'll have a workaround before the fix, I'll let you know.

**Comment by iamisti** [comment]
@allumbra please check the new `mdt-row` feature (in table attributes).
It's support data changes, so hopefully exactly that what you need.
