### ISSUE TITLE
Failed to execute 'appendChild' on 'Node' when json data is not a string

### ISSUE THREAD

**Issue by gtwardus** [iamisti/mdDataTable#268]
I noticed that when using AJAX pagination I can only display string-data columns. When the column is read from an integer json value (like {"count":70}) the column displays nothing and in the console I get following error:

TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at append (http://localhost/bower_components/angular/angular.js:3660:15)
    at JQLite.(anonymous function) [as append] (http://localhost/bower_components/angular/angular.js:3776:17)
    at http://localhost/bower_components/md-data-table/dist/md-data-table.js:1380:33
    at Scope.$digest (http://localhost/bower_components/angular/angular.js:17832:23)
    at Scope.$apply (http://localhost/bower_components/angular/angular.js:18098:24)
    at done (http://localhost/bower_components/angular/angular.js:12078:47)
    at completeRequest (http://localhost/bower_components/angular/angular.js:12287:7)

Can I do something to fix this besides changing the backend with adding quotes to make the count parameter a string?

**Comment by coopernewby** [comment]
changing line 1377 worked for me:
`element.append(val);` 
to
`element[0].append(val);`
 I think its a JQlite error. The pull request was merged but then overwritten for some reason:
https://github.com/iamisti/mdDataTable/pull/223/files

This is relevant as well:
https://github.com/angular/angular.js/issues/11446

**Comment by coopernewby** [comment]
https://github.com/angular/angular.js/issues/11446

**Comment by gtwardus** [comment]
Awesome. I have placed the change to my code locally and it works great. Thanks a lot! Closing this issue.

**Comment by zuhrasofyan** [comment]
Any news regarding this error? Mine still got the same error when I paired v 2.2.0 with angular 1.6.3.
and it would be great to ironing the issue withuot having to edit the source manually...

**Comment by evaldsurtans** [comment]
With latest Angular 1.x.x version it still does not work, it can be fixed by changing
`element.append(val);`
to
`element.append('<span>' + val + '</span>');`
