### ISSUE TITLE
ROWID NOT WORKING!!!!!!

### ISSUE THREAD

**Issue by gerome0123** [iamisti/mdDataTable#273]
```
  mdt-table mdt-row="{data: clients,'table-row-id-key': 'id','column-keys': ['name', 'company_address', 'home_address']}"
      mdt-header-row
        mdt-column align-rule="left" Name
        mdt-column align-rule="left" Company Address
        mdt-column align-rule="left" Home Address

      mdt-custom-cell column-key="name"

        a ng-href="/clients/{{rowId}}" {{value}}
```

when i hover in to my href it only gives me this localhost:5000/clients/

**Comment by alan-K-R** [comment]
have not tested this but shouldn't it by "id" instead of "rowId" in your href?

**Comment by gerome0123** [comment]
thanks for the reply @alan-K-R with braces or not???

**Comment by gerome0123** [comment]
not working </3

**Comment by gerome0123** [comment]
@iamisti <3

**Comment by rvt** [comment]
are you sure your client's data set has a id?

**Comment by alan-K-R** [comment]
Your hover event should consume the selected-row callback function, example is https://codepen.io/iamisti/pen/OMvbMj

**Comment by gerome0123** [comment]
thanks for the reply @rvt yes i'm sure <3

**Comment by gerome0123** [comment]
@alan-K-R but i need href not selected row :)

**Comment by gerome0123** [comment]
$scope.clients = [{
    "id": 2,
    "classification_id": 1,
    "employee_id": 51,
    "name": "Lorem ipsum dolor sit amet, consectetuer adipiscing eli",
    "home_address": "Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,",
    "company_address": "Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,",
    "tin_no": "123123123",
    "tax_exempted": true,
    "remarks": "Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes,",
    "created_at": "2017-01-12T12:48:33.269+08:00",
    "updated_at": "2017-01-13T16:39:18.513+08:00"
  }]

@rvt here's my sample

**Comment by alan-K-R** [comment]
I thought your problem was the rowid not the rest of the URL content? Selected row callback returns row values, get that in a scope object you create and that object name,working example would be cool to see and we can test🤓

**Comment by gerome0123** [comment]
i just follow this guide http://codepen.io/anon/pen/vgyvYv

and change the ng-href={{rowId}} and its working but when i test in my web it is not working </3

**Comment by gerome0123** [comment]
i update my mddatatable repo
