### ISSUE TITLE
Getting sorted direction and sorted column to controller

### ISSUE THREAD

**Issue by anushkamds** [iamisti/mdDataTable#295]
Hi,
Is there any way, where i can get the sorted column and it direction in to my controller which controller the table. Also, is there are any way to get the what are the visible column which I choose from the drop down. 
Because I need to save those configurations to save in locally, if you comes back those settings would stay the same.

Thank you,
Guys.

**Comment by anushkamds** [comment]
found the way, sorry guys. :)

**Comment by mchurichi** [comment]
Hey @delockdown how did it? I also need to save the state, go to a different page, and then apply the same sort/current page when back ... already figure out that I can save the current state when calling the mdt-row-paginator function to get the data, but still no idea how to restore it back, thanks
