### ISSUE TITLE
error when hovering over headers 

### ISSUE THREAD

**Issue by camarena-jonatan** [iamisti/mdDataTable#317]
angular.js:14525 Error: Text for the tooltip has not been provided. Please include text within the mdTooltip element.
    at showTooltip (angular-material.js:23680)
    at onVisibleChanged (angular-material.js:23674)
    at angular-material.js:23659
    at angular.js:20178
    at e (angular.js:6274)
    at angular.js:6554

**Comment by vanheerdena** [comment]
You need to define a column-definition like so

`<mdt-column align-rule="right" column-definition="Delivery Start">Delivery Start</mdt-column>`

**Comment by camarena-jonatan** [comment]
thanks that solved my issue
