### ISSUE TITLE
Editable Field Not working

### ISSUE THREAD

**Issue by abhisheksreesaila** [iamisti/mdDataTable#41]
I am trying to use your "editable-field" for "md-data-table-cell" and the cell remains the same. I took the demo project and tried to edit to playaround it

**Comment by iamisti** [comment]
Hi @abhisheksreesaila ,
I'm sorry but this feature is still under development. Lot of work needed for this component, but I'm just not at that phase yet.
Hope you understand. Let's hope it can be there soon :)

**Comment by iamisti** [comment]
fixed with v1.4.0
Check out the demo page to see how it works.
