### ISSUE TITLE
Support for angular material virtual repeat

### ISSUE THREAD

**Issue by franko-s** [iamisti/mdDataTable#52]
Any thoughts on adding support for virtual repeat?
I think it'd go very well with adding vertical scrolling with a fixed header. Effectively laying the groundwork for performant infinity scrolling.

**Comment by iamisti** [comment]
Sure, that's in my todo list also. I'm very close to start that feature too.
I assume we'll have it latest at the end of january (most probably sooner)

**Comment by franko-s** [comment]
Great. looking forward to it.
Thanks

**Comment by SalmanZafar214** [comment]
+1

**Comment by manifestarium** [comment]
+1,000,000 :)

**Comment by iamisti** [comment]
alright, it went up to my priority list. So I've started to work on it. Next release will contains it. Probably within few days.

**Comment by iamisti** [comment]
From now you guys can enjoy the new virtual repeat feature with the `1.2.0` release.
Check out the demo page: http://iamisti.github.io/mdDataTable/.

**Comment by SalmanZafar214** [comment]
@iamisti  Nice work bro . but does it support loading content on demand ?

**Comment by iamisti** [comment]
Yes it does, as long as you use `mdt-row` attribute for `mdt-table` :)

**Comment by filiplikavcan** [comment]
Excelent! Thank you. Can you please show us an example of lazy content loading (on demand)?

**Comment by iamisti** [comment]
@filiplikavcan  It's on the demo page, 'ajax support' section

**Comment by filiplikavcan** [comment]
I tried but it won't load next page. Can you please paste a JS/HTML here so I can figure out what's wrong with my code?

**Comment by iamisti** [comment]
as I told, it's on the demo page :)
But here is it: [ajax support](http://codepen.io/iamisti/pen/BjpNow)

**Comment by filiplikavcan** [comment]
I saw the demo but there "virtual repeat" is not used in it. ;)

**Comment by iamisti** [comment]
@filiplikavcan ah I got you now. So you want to have continously loading and scrollable table with virtual repeat. 
Why pagination is not a solution for you with ajax support?

**Comment by filiplikavcan** [comment]
I need to achieve infinite scroll like this http://codepen.io/pen?

**Comment by iamisti** [comment]
Alright, I'll take a look at it and try to provide the possibility to have the same.

**Comment by michaelkrog** [comment]
Did you look into the infinite scroll?

**Comment by lobo87** [comment]
any updates on this?

**Comment by alexandreprado** [comment]
Hi @iamisti, do you think it is "implementable"? It would be a great feature.

Thank you!
