### ISSUE TITLE
Column header binding

### ISSUE THREAD

**Issue by davidcui2** [iamisti/mdDataTable#55]
I believe it's a new issue introduced since 1.0.x. 

Tested using the demo [codepen](http://codepen.io/zhc/pen/vLgPXd), with `{{$scope.Calories = "Calories";}}`.

Bind element will be shown as the row content `{{header}}` rather than desired values set in js.

    <mdt-header-row>
        <mdt-column>
            {{header}}
        </mdt-column>
    </mdt-header-row>

Correct me if I'm supposed to use something else instead.

**Comment by iamisti** [comment]
I'm working on it.

**Comment by iamisti** [comment]
Fixed version released in `v1.1.2`

**Comment by davidcui2** [comment]
I updated the source file using bower, which is now v1.1.2. But I can't see the resolved result, as well as on the [codepen](http://codepen.io/zhc/pen/vLgPXd). Do you need to update the dist folder?

Sorry if it's stupid. I'm not good at using Bower.

**Comment by iamisti** [comment]
You completely right, sorry. Few minutes and it'll be there.

**Comment by iamisti** [comment]
@davidcui2 please try now with v1.1.3 and tell me if it was working. Thanks!

**Comment by davidcui2** [comment]
All happy now. Good job!
