### ISSUE TITLE
Ajax + custom fields

### ISSUE THREAD

**Issue by Stormsher** [iamisti/mdDataTable#58]
Need a feature to use Ajax loading and virtual repeat...
For example I need to show all record from database with custom html fileld (additional actions for example)
Can you help to realize that?

**Comment by iamisti** [comment]
@Stormsher virtual repeat is under development right now. You have to be patient for few days until I get it implemented. 
Additional actions are also in the next steps but I can't tell you when exactly. In this month for sure.

**Comment by manifestarium** [comment]
Aww, I was hoping this grid would do that... Kind of defeats the purpose of virtual repeat if it has to load all the rows upfront

**Comment by iamisti** [comment]
Now there is an html support for `mdt-row` attribute. Does it help you?
It's still not working with virtual-repeat, but maybe pagination is enough for you.

**Comment by iamisti** [comment]
Also there is `mdt-custom-cell` you can use. Check the documentation.
