### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by FraGoTe** [iamisti/mdDataTable#60]
Hi, is there a way to refresh the table via ajax with an external button?

**Comment by iamisti** [comment]
Hi @FraGoTe, this is not possible at the moment. Only if you provide data with the non-ajax way. That case it'll automatically refresh when your data object changes.

**Comment by bigosmallm** [comment]
Is there a workaround for this?  What is the best way to refresh the table which has pagination via ajax?

**Comment by bigosmallm** [comment]
Update: I figured out that we can use the ng-if to momentarily remove the table off the DOM and re-add it.  This causes the table to instantiate itself again and call the paginator callback function, essentially refreshing it externally.

Here is a codepen showing this solution: [http://codepen.io/anon/pen/yJVXLw](http://codepen.io/anon/pen/yJVXLw)

**Comment by iamisti** [comment]
It is possible for a while which gives you a much better performance and user experience:

**From the documentation**

|:white_check_mark:| mdt-trigger-request                 | function(loadPageCallback) | optional, if `mdt-row-paginator` set, provides a callback function for manually triggering an ajax request. Can be useful when you want to populate the results in the table manually. (e.g.: having a search field in your page which then can trigger a new request in the table to show the results based on that filter.  |

**Comment by NBAMj** [comment]
Can you provide an example of how to use mdt-trigger-request when using Ajax Column Filter Support ?
the function mdt-trigger-request is being called after my ajax insert call, but the passed parameter "loadPageCallback" is undefined .

**Comment by Spragalas** [comment]
How to use that?

**Comment by ryankidd** [comment]
I'm on my first Angular project.  I may not be the best to explain, but this works.  

**Add this to your mdt-table directive:** 

mdt-trigger-request="getLoadResultsCallback(loadPageCallback)"

**Now in your controller, add this:**

var loadPageCallbackWithDebounce;
$scope.getLoadResultsCallback = function(loadPageCallback){
     loadPageCallbackWithDebounce = _.debounce(loadPageCallback, 1000);
}

Now whenever you call loadPageCallbackWithDebounce(), the paginator function gets run again.

Here is an example of how to call:

$scope.deleteInvoices = function(rows){

        _.forEach( rows, function( value, key ) {
                Invoices.delete({id:value});
        });  

        if(loadPageCallbackWithDebounce){
              loadPageCallbackWithDebounce();  
       }        
});
}

**Comment by nojaf** [comment]
@Spragalas , maybe a bit late but there is an example on http://codepen.io/iamisti/pen/RRrjLk?editors=1010
