### ISSUE TITLE
(DEMO > search) TypeError: _.get is not a function

### ISSUE THREAD

**Issue by OskHa** [iamisti/mdDataTable#62]
TypeError: _.get is not a function
    at md-data-table.js:244
    at Function.m.each.m.forEach (underscore-min.js:5)
    at addRawDataToStorage (md-data-table.js:243)
    at Object.fn (md-data-table.js:233)
    at r.$digest (angular.min.js:131)
    at r.$apply (angular.min.js:134)
    at g (angular.min.js:88)
    at R (angular.min.js:92)
    at XMLHttpRequest.v.onload (angular.min.js:93)

HTML:
```
<md-card style="margin:0px">
        <md-subheader>Filter by search</md-subheader>

        <md-input-container style="margin:15px;">
            <label>Search</label>
            <input type="text" ng-model="filterName">
        </md-input-container>

        <div ng-hide="true">
            {{(filteredItems = (nutritionList | filter: filterName))}}
        </div>
    </md-card>
    <mdt-table
        paginated-rows="{isEnabled: true, rowsPerPageValues: [5,10,20,50]}"
        mdt-row-paginator-error-message="Error happened during loading nutritions."
        mdt-row="{
                'data': filteredItems,
                'table-row-id-key': 'id',
                'column-keys': ['name', 'calories', 'fat', 'carbs', 'protein', 'sodium', 'calcium', 'iron']
        }">
        <mdt-header-row>
            <mdt-column align-rule="left">Dessert (100g serving)</mdt-column>
            <mdt-column align-rule="right">Calories</mdt-column>
            <mdt-column align-rule="right">Fat (g)</mdt-column>
            <mdt-column align-rule="right">Carbs (g)</mdt-column>
            <mdt-column align-rule="right">Protein (g)</mdt-column>
            <mdt-column align-rule="right">Sodium (mg)</mdt-column>
            <mdt-column align-rule="right">Calcium (%)</mdt-column>
            <mdt-column align-rule="right">Iron (%)</mdt-column>
        </mdt-header-row>
    </mdt-table>
```

tested with dependencies:

```
"dependencies": {
    "jquery": "~2.1.4",
    "angular-material": "master",
    "components-font-awesome": "master",
    "angular-messages": "~1.4.8",
    "angular-route": "~1.4.8",
    "angular-loader": "~1.4.0",
    "angular-mocks": "~1.4.8",
    "angular-paging": "~2.1.0",
    "ngmap": "~1.16.7",
    "angular-environment": "~1.0.3",
    "mdDataTable": "~1.2.0",
    "underscore": "~1.8.3",
    "lodash": "~3.10.1",
    "angular-aria": "~1.4.9",
    "angular-animate": "~1.4.9"
  }
```

Any ideas ?

**Comment by OskHa** [comment]
Found a sollution. Its just a load order wich seems to be very important!

ALWAYS load lodash after mdDataTable files.

**Comment by iamisti** [comment]
You're right. It has a dependency against lodash.
The question is how we can ensure that you load lodash with the component.

**Comment by OskHa** [comment]
Well, it would be great to have a notice in documentation.

I just had to update my gulp script and change the script order. But it was a small pain to find the issue

**Comment by iamisti** [comment]
Yes, but for me the main problem is that it doesn't have an angular modules wrapper, so it's easily skippable and error prone.
Here: [app.js](http://github.com/iamisti/mdDataTable/blob/master/app/modules/app.js)

I'll create/find a wrapper for that component and take care it's loaded on start.
Thanks for creating the issue!

**Comment by OskHa** [comment]
with a pleasure! i find your module awesome. if you need some contributors, let me know.

cheers.

**Comment by iamisti** [comment]
Thank you!

Contributions are always very welcome! Whenever you want. :+1:

**Comment by shriharry** [comment]
Guys ,

Can you check last comment of `[63](https://github.com/iamisti/mdDataTable/issues/63)`.
