### ISSUE TITLE
Refresh data, issue with un-shift 

### ISSUE THREAD

**Issue by SalmanZafar214** [iamisti/mdDataTable#65]
Hi

on adding new item in array always pushed down . where as i m doing un-shift  and its expected to be added at top.

http://codepen.io/salmanzafar/pen/eJMmgM
can someone help me ?  why its pushing down

**Comment by iamisti** [comment]
Have you tried using `mdt-row` attribute of `mdt-table` instead of using the element `mdt-row` directive?
Example usage: [codepen example](http://codepen.io/iamisti/pen/bEBKYx)

**Comment by SalmanZafar214** [comment]
Thanku it does work with mdt-row attribute of mdt-table .
