### ISSUE TITLE
Replace mdt-row attribute with mdt-row element

### ISSUE THREAD

**Issue by filiplikavcan** [iamisti/mdDataTable#66]
It would be more consistent if a row is defined by mdt-row element no matter where the data comes from. An AJAX response should update $scope collection and the rest is up to Angular. ;)

**Comment by filiplikavcan** [comment]
Never mind. It already works that way. :)

**Comment by iamisti** [comment]
Yes it would be, but then you there a problem facing against you. Angular transclusion and the way it works.
I've described the flow here: https://github.com/iamisti/mdDataTable/blob/master/app/modules/app.js

The main problem is that even when u delete a row from your data source, it's been already transcluded and added to the data has been already added to the data storage. There is no clean way to detect the changes decently.

But I'm very open for suggestions/pull requests. Someone who is pro with transclusions.

**Comment by filiplikavcan** [comment]
I'm not sure I understand the problem. If a row is deleted all what is needed is to call a pagination method which would retrieve updated list of rows and by updating the collection in refreshes the table.

Another issue with the mdt-row is that a html markup cannot be used as a content of a cell (for example buttons, etc.).

**Comment by iamisti** [comment]
You right, it was just a quick workaround for that problem, but it lacks of html support.
I'll try to figure out how to make mdt-row element attribute flexible. Until that if anybody has an approach to fix that, very welcome to push a pull request. 
In the meantime I'll dig into myself to solve the problem.

**Comment by filiplikavcan** [comment]
I would ditch the attribute and focus on the element. :-) IMHO, supporting both attribute and element will be causing a lot of troubles. I really appreciate your effort and fast response!

**Comment by iamisti** [comment]
Sure, you right. I'd rather have one too because it can be error prone. :+1: 
And I really appreciate your suggestion too!

**Comment by iamisti** [comment]
@filiplikavcan now you can also use `mdt-custom-cell` to generate your own cell content.
With conjuction of `mdt-row` attribute.

**Comment by filiplikavcan** [comment]
👍  Thanks.
