### ISSUE TITLE
ng-repeat within a cell

### ISSUE THREAD

**Issue by cunla** [iamisti/mdDataTable#68]
Having a html-content cell with `<div ng-repeat...>` doesn't work

**Comment by iamisti** [comment]
@cunla I'm not sure I understood your problem. Can you please extend one of the demo page to show the issue that you found? (see demo pages and click on the codepen logo to change it)

**Comment by cunla** [comment]
[codepen ](http://codepen.io/anon/pen/ZQRMXL?editors=1010)- check the Name column

**Comment by iamisti** [comment]
Thanks, I'll look into the problem and fix it as soon as I can.

**Comment by bigosmallm** [comment]
Has this bug been fixed?

**Comment by iamisti** [comment]
@bigosmallm @cunla yes I hope it has been fixed.
Now you can use `mdt-custom-cell` which gives you the power to render your own cell the way you want. 

Please check the documentation and let me know if it's not yet solved  for your problem you had.
