### ISSUE TITLE
"TypeError: b.module(...).decorator is not a function" after 'md.data.table' module add

### ISSUE THREAD

**Issue by jangidgirish** [iamisti/mdDataTable#69]
Hello,

I have installed 'md.data.table' from `bower`, and i am getting `b.module(...).decorator` error, can you please take a look, is there any version issue, i am using angular material theme, please see  `bower.json` file and bug screen shot
![capture](https://cloud.githubusercontent.com/assets/4018017/12703664/796b32ca-c86e-11e5-8927-89daaac50635.PNG)
![capture1](https://cloud.githubusercontent.com/assets/4018017/12703674/b01a3848-c86e-11e5-8365-a650d4bf8d3a.PNG)

thank you
Girish

**Comment by iamisti** [comment]
Looks like you are using the wrong bower dependency :)
Try this: `"mdDataTable": "1.3.0"`

**Comment by TAMMENY** [comment]
How did you solve this problem ?

**Comment by iamisti** [comment]
Using the newest version of the component. Do you still have the problem?

**Comment by jangidgirish** [comment]
@TAMMENY i updated version

**Comment by TAMMENY** [comment]
@iamisti Yes i do

**Comment by TAMMENY** [comment]
@jangidgirish I have been using the latest version.

**Comment by TAMMENY** [comment]
When i using the latest version of angularjs, the problem is solved. Thank you all.

**Comment by iamisti** [comment]
Great, good to know!
