### ISSUE TITLE
Delete rows on the fly

### ISSUE THREAD

**Issue by shak18** [iamisti/mdDataTable#72]
Ok so im experiencing some weird behaviour i need to delete rows on the fly with a button that without asking any questions or have the row selected it deletes the row, by now i have a funcion that deletes the object from the source array but after it executes the row still there, only if i delete all rows one by one and the object gets empty then all of them dissapear can someone please point me in the right direcction or tell me if is there a way to force the update of the visible data of the table tnx

**Comment by iamisti** [comment]
Have you tried using `mdt-row` attribute on `mdt-table` instead of using the `<mdt-row>` element?

**Comment by shak18** [comment]
but a need to use html-content on cells it is possible by the atribute?

**Comment by webcane** [comment]
@shak18 You can try to use md-custom-cell to solve it. see [example](http://codepen.io/webcane/pen/bwqxPR)

**Comment by iamisti** [comment]
exactly, you can use it via `md-custom-cell`. Thanks @webcane for the reply!
