### ISSUE TITLE
Register as npm module 

### ISSUE THREAD

**Issue by matheuspoleza** [iamisti/mdDataTable#74]
It would be great to install mdDataTable like <code>npm install md-data-table --save</code>.

**Comment by jaoued** [comment]
+1

**Comment by iamisti** [comment]
Alright, will do that in the weekend.

**Comment by iamisti** [comment]
Registered https://www.npmjs.com/package/md-data-table

**Comment by jaoued** [comment]
The link to github repo is wrong `httpq://github.com/angular/iamisti ` instead of `https://github.com/iamisti`

**Comment by iamisti** [comment]
Wow that was a silly mistake. Thanks for pointing it out.

**Comment by matheuspoleza** [comment]
@iamisti cool! :+1:
