### ISSUE TITLE
[Documentation] improve pagination explanation 

### ISSUE THREAD

**Issue by MikeElghali** [iamisti/mdDataTable#84]
Hi,

Actually, we see in the doc the "Pagination" section which refer to automatic pagination from a collection.
And in the "Ajax support", a custom pagination calculated from response data.

I think you can add "Simple Pagination" (refer to actual Pagination section ) and "Custom Pagination" (refer to actual Ajax Support).

"Ajax support" section could be simplify to just explain automatic filling from an external ressource.  

Regards.

**Comment by iamisti** [comment]
It's a good remark, thanks. Will do that as well.
