### ISSUE TITLE
[Documentation] add kitchen sink section

### ISSUE THREAD

**Issue by MikeElghali** [iamisti/mdDataTable#85]
Hi,

In contrast to "Basic" section, you can add "Kitchen sink" section at the top to display all functionalities in only one section.

So, user can see what this package can do.

Regards.

**Comment by iamisti** [comment]
Like the idea but it's almost not possible to show all functionalities on one page. Every main function has different setups, some cover other, etc. How did you image that page exactly? Show as much as I can?

**Comment by jaoued** [comment]
In the best world : a guide page (an example http://vuejs.org/guide/) and api page (refer to actual readme file).
