### ISSUE TITLE
[Donation] Paypal refused to send you money

### ISSUE THREAD

**Issue by MikeElghali** [iamisti/mdDataTable#87]
Hi,

Paypal says that you can't receive money for now :

![capture d ecran 2016-02-28 a 21 23 14](https://cloud.githubusercontent.com/assets/2301050/13381652/8cdcb668-de61-11e5-9c7c-968d1dddb35e.png)

I can't pay you coffees :(

Regards.

**Comment by iamisti** [comment]
Hi @jaoued 

Thank you very much, really appreciate it. I'm still waiting for the address verification and then my account became a fully functional account. May I leave this ticket open and let you know when it happened?

**Comment by jaoued** [comment]
Ok, I will try again later and come back to tell you if it works.
