### ISSUE TITLE
[NPM] Add your dependencies

### ISSUE THREAD

**Issue by jaoued** [iamisti/mdDataTable#88]
Hi,

It seems you use `angular-material-icons` package.
So you need to refer this in the npm package description (refer to issue #86) : 

```json
"dependencies": {
  "angular": "^1.5.0",
  "angular-animate": "^1.5.0",
  "angular-aria": "^1.5.0",
  "angular-material": "^1.0.5",
  "angular-material-icons": "^0.6.0"
},
```

Regards.

**Comment by iamisti** [comment]
yes, you right - again -. I didn't think about the dependencies that might occur when you only use npm.
I'd rather copy the dependencies I defined in bower file:

```json
"dependencies": {
    "jquery": "~2.1.4",
    "lodash": "~3.10.1",
    "angular": "~1.4.8",
    "angular-sanitize": "~1.4.8",
    "angular-animate": "~1.4.8",
    "angular-material": "1.0.2",
    "angular-material-icons": "~v0.6.0"
}
```

Is that still fine for you?
