### ISSUE TITLE
mdDataTable search not working

### ISSUE THREAD

**Issue by chaoticbit** [iamisti/mdDataTable#92]
used to given example from the demo 
`<div ng-hide="true">
         {{(filteredItems = (nutritionList | filter: filterName))}}
</div>`
`<mdt-table mdt-row="{'data': filteredItems,'table-row-id-key': 'id','column-keys': ['name', 'calories', 'fat', 'carbs', 'protein', 'sodium', 'calcium', 'iron']}">`

but rows are blank. There are no elements in `<mdt-row>`

**Comment by chaoticbit** [comment]
Found the solution for data not getting rendered while using search.
In `dist/md-data-table.js` at line 1127 in method `mdtAddHtmlContentToCellDirective()` change `element.append(val.value)` to `element.append(val)`

And in `md-data-table-templates.js` in `$templateCache.put("/main/templates/generateRows.html"` after `<!-- non editable field -->` remove `ng-if=\"cellData.attributes.editableField === false\"` from `<span mdt-add-html-content-to-cell=\"cellData\"></span>` @iamisti

**Comment by jexneedls** [comment]
+1

**Comment by iamisti** [comment]
I know guys. Sorry for this issue. I did something with the latest release which causing that. Try with an older version and it will work. This can be a temporary solution meanwhile I'm trying to solve the problem.

**Comment by jex310** [comment]
+1

**Comment by maxhan247** [comment]
+1

**Comment by eduardosanzb** [comment]
+10000000

**Comment by gss-patricia** [comment]
+1

**Comment by iamisti** [comment]
Try to use an older version of this component and it will work.
In the meantime, I'll try to fix it in this week.

**Comment by iamisti** [comment]
Fixed with v1.5.0
