### ISSUE TITLE
mdDataTable dependency injection giving error

### ISSUE THREAD

**Issue by buhtig61** [iamisti/mdDataTable#93]
I was working previously with angular-material-data-table from github and its dependency md.Data.Table worked fine in my angular module, but now when I am working with your package, after installing in npm and including scripts and css in the index file, when i put mdDataTable in my module, it shows injection error in the console. 

Here is the code for eg: 

`angular.module("pouchapp", ["ngMaterial","ngAria","ngAnimate", "ui.router","mdDataTable"])`

Also I have installed your package in bower and included all files in my index.html

**Comment by jaoued** [comment]
Hi,

You need 'ngMdIcons' dependency from angular-material-icons npm package (or bower as you want).

For more detail see #86 

Regards.

**Comment by buhtig61** [comment]
Thanks it worked

**Comment by burakcosk** [comment]
I am new to web-development, how do we include all files to index.html ? So i believe one is like this

    <script src="bower_components/mdDataTable/dist/md-data-table-templates.js"></script>
how am i going to include others? to where which part of code .

Sorry for the dummy question, thanks.

**Comment by ricardofilho6** [comment]
I had this problem, i included the files mentioned above and got some errors anyway. After that i updated bower and now it's working o/

https://stackoverflow.com/questions/42270033/unknown-provider-mapprovider
