### ISSUE TITLE
md-virtual-repeat-sizer goes through the roof with virtual-repeat

### ISSUE THREAD

**Issue by alekseyl** [iamisti/mdDataTable#98]
PS code same as sample.

![issue1](https://cloud.githubusercontent.com/assets/2870243/13853763/ea62ddcc-ec70-11e5-92de-0e05ecdeeb65.PNG)
![issue2](https://cloud.githubusercontent.com/assets/2870243/13853764/ea89c1b2-ec70-11e5-9109-86f2b0e4d489.PNG)

**Comment by iamisti** [comment]
@alekseyl 
Hopefully fixed already. Please let me know if the issue is still present.
