### ISSUE TITLE
Sorting doesn't sort right

### ISSUE THREAD

**Issue by Sanchokus** [iamisti/mdDataTable#99]
Sorting in [Live Demo](http://iamisti.github.io/mdDataTable/) doesn't sort for almost all columns, for example, for "Animated Sort Icon" page:
- for first column - Eclair, Cupcake, Gingerbread
- for "Sodium" column - 337, 413, 327

I have the same problem with my mdDataTable installed from Bower 2 days ago. Are there any possible workarounds?

**Comment by surfjedi** [comment]
+1

**Comment by rhorber** [comment]
Same here.
I tried the sort-by attribute, but I don't get it to work...

**Comment by iamisti** [comment]
@Sanchokus, @surfjedi Working on it, you'll have the fix in few days.

**Comment by iamisti** [comment]
Fixed and shipped with v1.6.6
